### ISSUE TITLE
Structure of the repo does not align with RAMP Standard

### ISSUE THREAD

**Issue by jason-fox** [ramp-eu/JS2SF#1]
Please move:

-  the texts from https://github.com/ramp-eu/JS2SF/blob/master/ROSEAP/ReadMe.md i nto the root readme.
- The docs from https://github.com/ramp-eu/JS2SF/tree/master/ROSEAP/docs into docs
- Use the exisiting files in /docs to structure the content.
- Amend the `mkdocs.yml` file if as necessary.

Eventually the docs should be set up as a https://readthedocs.org/ project  then update the project description to point to the documentation:

![Screenshot 2021-04-28 at 09 22 44](https://user-images.githubusercontent.com/3439249/116363524-81253680-a803-11eb-98eb-9edfb04e29fd.png)

**Comment by OptidriveAdmin** [comment]
I copied the readme and the doc files. Still working on them but they are i the right spot  believe.
I can all installationg and configurztion files in one big file if it is required. I thougt the overview was easier when splitting up in smaller fragments.
I never used Readthe docs project (and i am not so familiar with md documents too). So if the startup is easy i can go that direction. What is your advice?.

**Comment by jason-fox** [comment]
> I copied the readme and the doc files. Still working on them but they are i the right spot believe
 ✔️ 

> I never used Readthe docs project. Is start-up easy:

Just log-in at `https://readthedocs.org/accounts/login/?next=/dashboard/` and you'll be prompted for your GitHub Account. The repo already has a working `mkdocs.yml` in the root of the repo. When importing a project most of the settings are self-explanatory. On the advanced settings you'll need to select **Documentation type: Mkdocs** and then click build.

You may need to place a config file called `.readthedocs.yml`  in the root as well:

```yml
version: 2

mkdocs:
  configuration: mkdocs.yml

python:
  version: 3.6
```

If you're still having difficulty, just temporarily add my GitHub user **jason-fox** as an admin of your readthedocs project and I should be able to diagnose your set-up and then delete myself thereafter.

**Comment by jason-fox** [comment]
It is probable that. `https://github.com/ramp-eu/JS2SF` will have to be public to get it to work. I will change the setting right now.

**Comment by OptidriveAdmin** [comment]
Ok. I think everything is working now. Also the read the docs project is setup and compiling.  You can check it at https://js2sf.readthedocs.io/en/latest/index.html.
So for now i keep this as the backbone of the documentation and will return to edit the contents.
