### ISSUE TITLE
Add missing badges & etc to README

### ISSUE THREAD

**Issue by jason-fox** [ramp-eu/JS2SF#2]
I have tidied up the `README` - the following badges should be re-added if/when you

```markdown

- [![Docker badge](https://img.shields.io/docker/pulls/ramp-eu/JS2SF.svg)](https://hub.docker.com/r/<org>/<repo>/)
- [![Build badge](https://img.shields.io/travis/ramp-eu/JS2SF.svg)](https://travis-ci.org/ramp-eu/TJS2SF/)
- [![Coverage Status](https://coveralls.io/repos/github/ramp-eu/JS2SF1/badge.svg?branch=master)](https://coveralls.io/github/ramp-eu/TTE.project1?branch=master)
- [![Codacy grade](https://img.shields.io/codacy/grade/99310c5c4332439197633912a99d2e3c)](https://app.codacy.com/manual/jason-fox/TTE.project1)
```

Obviously connecting the badges to your own  project rather than the dummy one.

The following items should also be updated

1 - The preferred license is APACHE - please replace and add your company name to the copyright holder
2 -  On the `readme` add your company name after the copyright symbol.
3 - The purpose of the component is unclear from the README, please amend the lede to better summarize what it does.

**Comment by OptidriveAdmin** [comment]
1. Done
2. Done
3. Title ia changed
