### ISSUE TITLE
Missing Dockerfile?

### ISSUE THREAD

**Issue by jason-fox** [ramp-eu/JS2SF#3]
The `README` states:

> A Dockerfile is also available for your use - further information can be found here

However the location does not contain a `Dockerfile` - just a `docker-compose`. Please add the `Dockerfile` or amend the text.

Similarly the docker link on the `README` is going nowhere:

```
| :whale: [Docker Hub](https://hub.docker.com/r/link-to-docker) |
| ------------------------------------------------------------- |
```

**Comment by OptidriveAdmin** [comment]
should point to the directory https://github.com/ramp-eu/JS2SF/tree/master/docker. Ichanged the link to an absolute path. Not relative. Still have to regenerate the readthe docs

**Comment by OptidriveAdmin** [comment]
I changed the readme file.

**Comment by jason-fox** [comment]
![Screenshot 2021-06-30 at 16 09 49](https://user-images.githubusercontent.com/3439249/123975472-a712b700-d9bd-11eb-8bbc-2a049594c769.png)

I'm still seeing this link on the `README`

**Comment by OptidriveAdmin** [comment]
ok understood it now
i missed that reference
