### ISSUE TITLE
Add test to CI

### ISSUE THREAD

**Issue by jason-fox** [ramp-eu/JS2SF#4]
Configure a CI system of your choice to re-add the missing badge
Delete the `.travis` if not using Travis CI. Consider adding a GitHub Action like the [Template Project](https://github.com/ramp-eu/TTE.project1/blob/master/.github/workflows/ci.yml) - this could also run the code analysis which is one of the missing CII points.

Your CI badge would then look like this:

```markdown
[![CI](https://github.com/ramp-eu/JS2SF/workflows/CI/badge.svg)](https://github.com/ramp-eu/JS2SF/actions?query=workflow%3ACI)
```

**Comment by OptidriveAdmin** [comment]
i tried to add this repository to an account on https://www.travis-ci.com/account/repositories . All repositories we are admin from are in the list but this one is not.  I do not know what rights i need to have to do so.
in the travis-ci.org the repository appeared but it is only available till end of may. So i switched to the .com variant.

**Comment by jason-fox** [comment]
Questions about potential cost is the reason my organization transferred to [GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions). You may find some inspiration from one of these [Pull Requests](https://github.com/search?q=GitHub+Action+travis+author%3Ajason-fox&type=Issues)

**Comment by OptidriveAdmin** [comment]
Github action is added and configured. Code is compiled at push action.
