### ISSUE TITLE
Correct the contributing guidelines

### ISSUE THREAD

**Issue by jason-fox** [ramp-eu/JS2SF#6]
The contributing guidelines currently state:

> - That the code is correctly formatted (`go fmt`).
> - That the commits are based on a reasonably recent `main`.
>  - That the author is listed in `AUTHORS`.
> - That the output from `go lint` and `go vet` is clean

This is not a Go project. The main branch is `master` not `main` and there is no `AUTHORS` file to edit.

**Comment by OptidriveAdmin** [comment]
corrections are made and committed

**Comment by jason-fox** [comment]
There is still a reference to the `main` branch.

**Comment by OptidriveAdmin** [comment]
done, used a search function this time.
